export interface ModuleBenefit {
  role: string;
  benefit: string;
}

export interface Module {
  slug: string;
  num: string;
  title: string;
  tagline: string;
  shortDesc: string;
  longDesc: string;
  icon: string;
  grad: string;
  features: string[];
  whoBenefits: ModuleBenefit[];
}

export interface ModuleGroup {
  category: string;
  categorySlug: string;
  categoryIcon: string;
  tagline: string;
  bg: string;
  pill: string;
  border: string;
  accentBar: string;
  headerGrad: string;
  modules: Module[];
}

export const moduleGroups: ModuleGroup[] = [
  {
    category: "Transport & Safety",
    categorySlug: "transport",
    categoryIcon: "bus",
    tagline: "Keep every child safe, every day",
    bg: "from-orange-50 to-amber-50",
    pill: "bg-linear-to-r from-orange-500 to-amber-500 text-white",
    border: "border-orange-200",
    accentBar: "bg-linear-to-b from-orange-400 to-amber-400",
    headerGrad: "from-orange-500 to-amber-500",
    modules: [
      { slug: "bus-tracking", num: "01", title: "Bus Tracking", tagline: "Track every bus, every stop, in real time", shortDesc: "Parents watch the bus move live on a map and get push alerts before pickup.", longDesc: "Parents know exactly where the school bus is at every moment of the journey. Drivers tap start and the system does the rest — GPS location streams live to parent phones, the admin dashboard, and the school gate in real time. No calls, no guessing, no waiting at the roadside.", icon: "bus", grad: "from-orange-400 to-amber-400", features: ["Live GPS map visible to parents in the mobile app","Driver app with one-tap route start, stop check-ins, and route end","Push notifications sent automatically when bus is 2 stops away","Trip history and replay for any past route","Multiple buses and routes managed from one dashboard","Bus status overview for admin — on-route, delayed, or completed"], whoBenefits: [{ role: "Parents", benefit: "See the bus on a live map and get a push alert before it arrives — no more standing at the roadside" },{ role: "Drivers", benefit: "Simple one-tap start and stop — no radio calls or WhatsApp messages required" },{ role: "Administrators", benefit: "Monitor all active buses from one dashboard with live status updates" }] },
      { slug: "pickup-management", num: "02", title: "Pickup Management", tagline: "Only authorised people collect your students", shortDesc: "Control who is allowed to collect a child — with a security blacklist.", longDesc: "Schools define exactly who is permitted to collect each child. A security blacklist instantly flags unauthorised individuals at the gate and the system keeps a complete timestamped log of every pickup event, giving schools and parents full accountability.", icon: "user-check", grad: "from-red-400 to-orange-400", features: ["Whitelist of approved guardians per child with photo ID","Security blacklist to flag and block unauthorised individuals","Digital confirmation when child is handed over","Full pickup history with timestamps and guardian identity","Gate officer app with instant guardian verification","Parent notifications when child is collected"], whoBenefits: [{ role: "Parents", benefit: "Complete peace of mind knowing only pre-approved guardians can collect your child" },{ role: "Gate Staff", benefit: "Instant on-screen guardian verification — no paper lists to search through" },{ role: "Administrators", benefit: "Full audit trail of every child pickup for safeguarding compliance" }] },
      { slug: "emergency-response", num: "03", title: "Emergency Response", tagline: "Prepared for anything — protocols, drills, and incident logs", shortDesc: "Protocols, drills, and incident logs — always ready for anything.", longDesc: "School Bus keeps emergency protocols, drill schedules, and incident reports in one secure place. When something happens, staff know exactly what steps to follow and administrators have a complete, timestamped incident record for compliance and reporting.", icon: "triangle-warning", grad: "from-rose-500 to-red-400", features: ["Emergency protocol library customisable per school","Drill scheduling, notifications, and completion tracking","Incident reporting with descriptions and photo attachments","Immediate broadcast alerts to all staff and parents on activation","Historical incident log for safety audits and compliance","Role-specific response checklists for different emergency types"], whoBenefits: [{ role: "Administrators", benefit: "Maintain full compliance with safety regulations and produce incident reports instantly" },{ role: "Teachers", benefit: "Access emergency protocols from any device — no need to find a physical folder" },{ role: "Parents", benefit: "Receive immediate notifications if an incident affects the school" }] },
      { slug: "visitor-management", num: "04", title: "Visitor Management", tagline: "A digital gate log for every person entering your school", shortDesc: "Digital check-in, photo capture, and a full gate entry log.", longDesc: "Every person entering the school is checked in digitally — name, purpose, host, and photo captured in seconds. Administrators see a live gate log from any device and can pull historical visitor reports for security audits without touching a paper register.", icon: "eye", grad: "from-amber-400 to-yellow-400", features: ["Digital check-in form at the school gate — faster than a paper book","Photo capture for every visitor on arrival","Automatic host staff notification when their visitor arrives","Pre-registration of expected visitors for instant check-in","Full entry and exit log with timestamps","Visitor report exports for security audits"], whoBenefits: [{ role: "Administrators", benefit: "Complete real-time visibility of everyone inside the school at any moment" },{ role: "Gate Staff", benefit: "Fast digital check-in with automatic host notification — no phone calls needed" },{ role: "Parents", benefit: "Pre-register visits online so gate check-in takes under 30 seconds" }] },
    ],
  },
  {
    category: "Academics",
    categorySlug: "academics",
    categoryIcon: "book-open-cover",
    tagline: "Everything teachers and students need",
    bg: "from-blue-50 to-indigo-50",
    pill: "bg-linear-to-r from-blue-600 to-indigo-600 text-white",
    border: "border-blue-200",
    accentBar: "bg-linear-to-b from-blue-500 to-indigo-500",
    headerGrad: "from-blue-600 to-indigo-600",
    modules: [
      { slug: "academics", num: "05", title: "Academics & Report Cards", tagline: "Terms, subjects, marks, and report cards — all in one system", shortDesc: "Terms, subjects, classes, report cards — one organised system.", longDesc: "Manage the full academic cycle from term creation and subject configuration to mark entry and report card generation. Teachers enter marks once and the system automatically calculates aggregates, generates rankings, and produces formatted report cards ready to share with parents — no spreadsheets required.", icon: "book-open-cover", grad: "from-blue-500 to-indigo-500", features: ["Academic year and term setup and management","Subject and class stream configuration","Mark entry per subject per student with validation","Automatic grade aggregation and class ranking","Report card generation in school-branded PDF format","Report card sharing directly to parent mobile app"], whoBenefits: [{ role: "Teachers", benefit: "Enter marks once and get instant aggregates — no more spreadsheet formulas" },{ role: "Administrators", benefit: "Generate and distribute all report cards school-wide in minutes" },{ role: "Parents", benefit: "View your child's academic performance and report card at any time from the app" }] },
      { slug: "attendance", num: "06", title: "Attendance", tagline: "Daily attendance with instant absence alerts to parents", shortDesc: "Daily student and staff attendance with absence alerts.", longDesc: "Teachers mark attendance digitally at the start of each day or period. The system instantly sends push notifications and SMS alerts to parents when a child is absent, and gives administrators a live dashboard showing who is in school right now and absenteeism trends over time.", icon: "clipboard-check", grad: "from-sky-400 to-blue-500", features: ["One-tap daily and period-by-period attendance marking","Automatic parent push and SMS alerts for absences","Staff attendance tracking with separate dashboard","Monthly and termly attendance reports per student and class","Chronic absentee flagging and early warning system","Head teacher attendance dashboard with live school-wide view"], whoBenefits: [{ role: "Teachers", benefit: "Complete daily roll call in under 60 seconds directly from a phone or tablet" },{ role: "Administrators", benefit: "Spot absenteeism trends early and intervene before they become a problem" },{ role: "Parents", benefit: "Receive an instant alert if your child doesn't arrive at school" }] },
      { slug: "timetable", num: "07", title: "Timetable", tagline: "Build and publish class timetables in minutes", shortDesc: "Build and share class timetables and period definitions.", longDesc: "Create complete class timetables by defining periods, assigning teachers to subjects and streams, and publishing with one click. Clash detection catches conflicts before publishing, and teachers and students can view their personal timetable from the School Bus app at any time.", icon: "time-oclock", grad: "from-indigo-500 to-violet-500", features: ["Visual timetable builder with period and break definitions","Teacher-to-subject-to-class assignment management","Automatic clash detection before publishing","Individual teacher and student timetable views in the app","Substitute teacher scheduling for absences","Timetable versioning — maintain multiple drafts before publishing"], whoBenefits: [{ role: "Administrators", benefit: "Build a complete term timetable in minutes, not days — with clash detection built in" },{ role: "Teachers", benefit: "Always know your current schedule, room, and any substitute assignments" },{ role: "Students", benefit: "Access today's timetable from the mobile app without a printed copy" }] },
      { slug: "forms", num: "08", title: "Forms & Assignments", tagline: "Custom forms, assignments, and digital submissions — paperless", shortDesc: "Custom form templates, assignments, and digital submissions.", longDesc: "Create any school document digitally — consent forms, homework assignments, surveys, or parent questionnaires. Parents and students receive them instantly in the School Bus app and submit responses without printing, signing, or physically returning a single page.", icon: "document", grad: "from-violet-500 to-purple-500", features: ["Custom form builder with text, choice, date, and file fields","Assignment creation and distribution to specific classes or groups","Digital submission and collection from parents and students","Deadline tracking with automatic reminders","Submission status dashboard showing who has and hasn't responded","File and photo attachment support for rich submissions"], whoBenefits: [{ role: "Teachers", benefit: "Distribute and collect assignments entirely digitally — no printing, no lost papers" },{ role: "Administrators", benefit: "Send school-wide consent forms and track completion rates in real time" },{ role: "Parents", benefit: "Receive, sign, and return consent forms without visiting the school" }] },
    ],
  },
  {
    category: "Finance & Admin",
    categorySlug: "finance",
    categoryIcon: "credit-card",
    tagline: "Full financial control at your fingertips",
    bg: "from-green-50 to-emerald-50",
    pill: "bg-linear-to-r from-green-600 to-emerald-500 text-white",
    border: "border-green-200",
    accentBar: "bg-linear-to-b from-green-500 to-emerald-500",
    headerGrad: "from-green-600 to-emerald-600",
    modules: [
      { slug: "fees-management", num: "09", title: "Fees Management", tagline: "Invoices, payments, and balances — fully automated", shortDesc: "Fee structures, invoices, payments, and balance reports.", longDesc: "Define fee structures per class and term, generate invoices in bulk, and track every payment in one place. Parents view outstanding balances and make payments directly from the mobile app, dramatically reducing the queue at the bursar's office and chasing of unpaid fees.", icon: "credit-card", grad: "from-green-500 to-emerald-500", features: ["Fee structure templates per class, term, and fee category","Bulk invoice generation for the entire school in one click","Payment recording for cash, mobile money, and bank transfer","Outstanding balance tracking per student with aged debt view","Parent fee statement and invoice view in the mobile app","Termly fee collection dashboard and reports for management"], whoBenefits: [{ role: "Bursars", benefit: "No more manual ledgers or spreadsheets — all payments recorded and reconciled automatically" },{ role: "Administrators", benefit: "Real-time fee collection rates with drill-down to individual students" },{ role: "Parents", benefit: "View your child's invoice and pay outstanding fees directly from the mobile app" }] },
      { slug: "registration", num: "10", title: "Registration", tagline: "From application to class placement in one workflow", shortDesc: "Full admissions workflow from application to class placement.", longDesc: "Manage student admissions from the first inquiry right through to class placement. Collect applications, track document submissions, make admission decisions, and automatically assign new students to classes and bus routes — all without a paper file or spreadsheet.", icon: "user-add", grad: "from-teal-500 to-green-500", features: ["Online application and inquiry capture from any device","Document checklist with upload and verification tracking","Admission decision workflow — approve, waitlist, or reject","Automatic class assignment and bus route allocation on admission","Joining fee invoice generation on acceptance","Re-registration workflow for returning students each term"], whoBenefits: [{ role: "Administrators", benefit: "Manage hundreds of applications without paper files — everything tracked in one place" },{ role: "Parents", benefit: "Submit applications online and track the admission status without visiting the school" },{ role: "Class Teachers", benefit: "New students automatically appear in your class roll on the start date" }] },
      { slug: "staff-management", num: "11", title: "Staff Management", tagline: "Payroll, leave, and performance — all in one place", shortDesc: "Payroll, payslips, departments, and performance reviews.", longDesc: "Manage your entire staff from one screen. Process monthly payroll, generate and distribute payslips, handle leave applications and approvals, and record performance evaluations — all linked to each staff member's digital profile and accessible from anywhere.", icon: "briefcase", grad: "from-emerald-500 to-teal-500", features: ["Staff profile and contract management with role assignment","Department and organisational structure configuration","Monthly payroll processing with deductions and allowances","Payslip generation and secure distribution to staff","Leave application, balance tracking, and approval workflow","Performance review records and appraisal history"], whoBenefits: [{ role: "Administrators", benefit: "Process the entire school payroll in minutes with automatic calculations" },{ role: "HR", benefit: "Maintain a single source of truth for all staff records, contracts, and appraisals" },{ role: "Staff", benefit: "View your payslip and apply for leave directly from the School Bus app" }] },
      { slug: "inventory", num: "12", title: "Inventory", tagline: "Assets, stock, and vendors — tracked and always under control", shortDesc: "Assets, consumables, vendors, and purchase requests.", longDesc: "Know exactly what the school owns and what it needs. Track assets such as computers, furniture, and equipment alongside consumable stock levels, raise purchase requests digitally, manage vendor relationships, and maintain disposal records — everything in one module.", icon: "box-open", grad: "from-lime-500 to-green-500", features: ["Asset register with category, condition, and location tracking","Consumable stock levels with automated low-stock alerts","Purchase request creation and approval workflow","Vendor directory with contact and order history","Disposal and write-off records with authorisation","Stock valuation and asset reports for management"], whoBenefits: [{ role: "Bursars", benefit: "Full visibility of school assets and expenditure — no more mystery spending" },{ role: "Administrators", benefit: "Approve or reject purchase requests from the dashboard in seconds" },{ role: "Store Keepers", benefit: "Raise purchase requests and track stock levels without paper forms" }] },
    ],
  },
  {
    category: "Campus Life",
    categorySlug: "campus",
    categoryIcon: "home",
    tagline: "A great environment for learning and living",
    bg: "from-purple-50 to-fuchsia-50",
    pill: "bg-linear-to-r from-purple-600 to-fuchsia-600 text-white",
    border: "border-purple-200",
    accentBar: "bg-linear-to-b from-purple-500 to-fuchsia-500",
    headerGrad: "from-purple-600 to-fuchsia-600",
    modules: [
      { slug: "dormitory", num: "13", title: "Dormitory", tagline: "Rooms, beds, night attendance, and exeats — all managed", shortDesc: "Rooms, bed allocations, night attendance, inspections, and exeats.", longDesc: "Built specifically for boarding schools, the Dormitory module replaces every clipboard and paper register. Handle room and bed allocation, run nightly electronic roll call in under 5 minutes, log dorm inspection scores, and manage student exeat requests — all from one place.", icon: "home", grad: "from-purple-500 to-violet-500", features: ["Room and bed configuration per dorm block and house","Student bed assignment and room allocation management","Nightly electronic roll call — completed in under 5 minutes","Dorm inspection scoring with historical trend reports","Exeat request, approval, and tracking workflow","Dorm master mobile app for on-the-go management"], whoBenefits: [{ role: "Dorm Masters", benefit: "Complete nightly roll call for an entire dorm in under 5 minutes — no paper register" },{ role: "Administrators", benefit: "Pull dorm inspection scores and occupancy reports at any time" },{ role: "Parents", benefit: "Request and track your child's exeat from the parent app without visiting school" }] },
      { slug: "health", num: "14", title: "Health", tagline: "Nurse consultations, medication, and health records — paperless", shortDesc: "Nurse consultations, medication records, and health history.", longDesc: "The school nurse logs every consultation, medication administered, and health complaint directly in the app — replacing stacks of paper health cards. Administrators can pull health reports in seconds and parents are notified whenever their child visits the nurse.", icon: "heart", grad: "from-pink-500 to-rose-500", features: ["Consultation logging with presenting complaint, diagnosis, and treatment","Medication administration records with dosage and times","Student health profile with allergies and chronic conditions","Automatic parent notification on nurse visit","Hospital referral records and follow-up tracking","Monthly health trend reports for school management"], whoBenefits: [{ role: "School Nurses", benefit: "Log every consultation in seconds from a phone — no paper cards to manage or lose" },{ role: "Administrators", benefit: "Pull health statistics and identify recurring conditions across the student body" },{ role: "Parents", benefit: "Receive an instant notification whenever your child visits the school nurse" }] },
      { slug: "canteen", num: "15", title: "Canteen", tagline: "Menus, stock, and meal records for students and staff", shortDesc: "Menus, stock, daily meal records for students and staff.", longDesc: "Track weekly menus, manage canteen stock in real time, and record daily meal service for students and staff. The canteen manager receives automatic low-stock alerts before key items run out, and management gets clear visibility of canteen costs and revenue.", icon: "utensils", grad: "from-orange-400 to-pink-500", features: ["Weekly menu planning and publishing to the parent app","Daily meal service recording per student and staff member","Real-time stock inventory with consumption tracking","Automated low-stock alerts for key items","Supplier and order management","Canteen revenue, cost, and wastage reports"], whoBenefits: [{ role: "Canteen Managers", benefit: "Know stock levels in real time and get alerts before you run out of anything" },{ role: "Administrators", benefit: "Track canteen revenue and costs without waiting for a monthly report" },{ role: "Parents", benefit: "See the school's weekly menu in the mobile app so children know what to expect" }] },
      { slug: "events", num: "16", title: "Events", tagline: "Plan school events and keep everyone informed", shortDesc: "Plan school events and communicate to the whole school.", longDesc: "Create and manage all school events — sports days, parent meetings, prize-givings, graduations, and more. Publish events to the shared school calendar and send targeted push notifications so parents and staff never miss an important date.", icon: "calendar", grad: "from-yellow-400 to-orange-400", features: ["Event creation with title, date, venue, and description","School-wide calendar view accessible in the parent and staff app","Push notification and SMS event reminders","RSVP collection and attendance tracking","Post-event photo sharing to the school community","Recurring event scheduling for regular activities"], whoBenefits: [{ role: "Administrators", benefit: "Coordinate and communicate all school events from one place — no email chains" },{ role: "Parents", benefit: "Never miss a sports day or parent evening with push notification reminders" },{ role: "Teachers", benefit: "Check the school calendar and add department events from the app" }] },
      { slug: "discipline", num: "17", title: "Discipline", tagline: "Incidents, behaviour points, and grievances — tracked fairly", shortDesc: "Incidents, behaviour points, and student grievances.", longDesc: "Record student behaviour incidents, apply merit and demerit points, and manage the grievance resolution process digitally. Administrators get a clear view of behaviour patterns across the school and can intervene early, while parents are kept informed of any serious incidents.", icon: "balance-scale-right", grad: "from-red-500 to-rose-500", features: ["Incident reporting by any staff member from any device","Merit and demerit point system with running totals","Behaviour history and pattern view per student","Parent notifications for serious incidents","Grievance logging and resolution tracking","Termly behaviour reports for school management"], whoBenefits: [{ role: "Teachers", benefit: "Report incidents instantly from a phone — no forms to fill or offices to visit" },{ role: "Administrators", benefit: "Identify behaviour patterns early and intervene before issues escalate" },{ role: "Parents", benefit: "Be kept informed of any serious incident involving your child in real time" }] },
      { slug: "library", num: "18", title: "Library", tagline: "Catalogue, borrowing, and resource management — fully digital", shortDesc: "Catalog, resource management, and borrowing system.", longDesc: "Replace the paper borrowing register with a fully digital library system. Catalogue all books and resources, manage borrowing and returns, track overdue items with automatic alerts, and get clear reports on library usage — freeing the librarian to focus on readers rather than paperwork.", icon: "bookmark", grad: "from-blue-400 to-indigo-500", features: ["Book and resource catalogue with search and filter","Borrowing and return management with due date tracking","Overdue tracking with automatic reminders to students and parents","Student borrowing history and reading records","Resource reservation system for upcoming classes","Library usage reports — most borrowed, overdue rates, and stock value"], whoBenefits: [{ role: "Librarians", benefit: "No more paper registers — manage the entire library from a tablet in real time" },{ role: "Students", benefit: "Search for available books and reserve them from the School Bus app" },{ role: "Administrators", benefit: "Know which resources are most used and where investment is most needed" }] },
    ],
  },
  {
    category: "Communication",
    categorySlug: "communication",
    categoryIcon: "megaphone",
    tagline: "Keep everyone in the loop, instantly",
    bg: "from-yellow-50 to-amber-50",
    pill: "bg-linear-to-r from-yellow-500 to-orange-400 text-white",
    border: "border-yellow-200",
    accentBar: "bg-linear-to-b from-yellow-400 to-orange-400",
    headerGrad: "from-yellow-500 to-orange-500",
    modules: [
      { slug: "announcements", num: "19", title: "Announcements & Messaging", tagline: "Replace WhatsApp groups with one official school channel", shortDesc: "Send targeted messages to parents, staff, or the whole school instantly.", longDesc: "Send announcements as push notifications, SMS, or in-app messages — targeted to individual parents, specific classes, all staff, or the entire school. One reliable, official communication channel replaces scattered WhatsApp groups, notice boards, and phone-call chains.", icon: "megaphone", grad: "from-yellow-400 to-orange-500", features: ["Targeted announcements by audience — all, class, role, or individual","Push notification, SMS, and in-app message delivery","Direct messaging between school and individual parents","Message delivery and read receipt tracking","Scheduled announcements for future dates and events","Emergency broadcast to all contacts with a single tap"], whoBenefits: [{ role: "Administrators", benefit: "Replace WhatsApp group chaos with one official, auditable school communication channel" },{ role: "Teachers", benefit: "Message all parents in your class with one tap — no number hunting" },{ role: "Parents", benefit: "Receive all official school communications in one place — never miss an important update" }] },
    ],
  },
];

export const allModules: Module[] = moduleGroups.flatMap((g) => g.modules);

export function findModule(slug: string): { module: Module; group: ModuleGroup } | null {
  for (const group of moduleGroups) {
    const mod = group.modules.find((m) => m.slug === slug);
    if (mod) return { module: mod, group };
  }
  return null;
}
